<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Pravin" failures="3" tests="9" name="Test" time="66.706" errors="0" timestamp="2023-12-05T19:58:14 IST">
  <testcase classname="testCases.LoginPageTest" name="loginToApplicationTest" time="0.816">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.poi.ss.usermodel.Cell.getStringCellValue()&amp;quot; because the return value of &amp;quot;org.apache.poi.ss.usermodel.Row.getCell(int)&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because the return value of "org.apache.poi.ss.usermodel.Row.getCell(int)" is null
at utility.ReadData.readExcel(ReadData.java:25)
at testCases.LoginPageTest.loginToApplicationTest(LoginPageTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginToApplicationTest -->
  <testcase classname="testCases.LoginPageTest" name="varifyTitleOfApplicationTest" time="0.042"/>
  <testcase classname="testCases.LoginPageTest" name="verifyURLOfApplication" time="0.044"/>
  <testcase classname="testCases.Cart_Page_Test_3" name="varifytritterLogoTest" time="0.038"/>
  <testcase classname="testCases.Cart_Page_Test_3" name="varifyyourCartTest" time="0.034">
    <failure type="java.lang.AssertionError" message="expected [Your Cart] but found [Your Car]">
      <![CDATA[java.lang.AssertionError: expected [Your Cart] but found [Your Car]
at testCases.Cart_Page_Test_3.varifyyourCartTest(Cart_Page_Test_3.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- varifyyourCartTest -->
  <testcase classname="testCases.Inventory_page_2_Test" name="add6ProductsTest" time="0.413">
    <failure type="java.lang.AssertionError" message="expected [6] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [4]
at testCases.Inventory_page_2_Test.add6ProductsTest(Inventory_page_2_Test.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- add6ProductsTest -->
  <testcase classname="testCases.Inventory_page_2_Test" name="remove2ProductsTest" time="2.607"/>
  <testcase classname="testCases.Inventory_page_2_Test" name="varifyproductsLableTest" time="0.051"/>
  <testcase classname="testCases.Inventory_page_2_Test" name="varifytritterLogoTest" time="0.04"/>
</testsuite> <!-- Test -->
